name: godot-build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Godot Export
      uses: firebelley/godot-export@v1.0.1
      with:
        # Base version. Patch versions are incremented when this action runs.
        # base_version: 0.0.1 
        # The download url of the 64 bit Linux Headless Godot executable
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2.1/Godot_v3.2.1-stable_linux_headless.64.zip
        # The url of the export templates corresponding to the Godot executable version
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2.1/Godot_v3.2.1-stable_export_templates.tpz
        # The relative path containing the "project.godot" file
        relative_project_path: ./
        # The name of the folder which templates are stored in. Looks like '3.1.1.stable.mono'. Can be found at %APPDATA\Roaming\Godot\templates on Windows and ~/.local/share/godot/templates on Linux.
        godot_template_version: 3.2.1.stable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: mkdir
      run: mkdir build
    - name: copy
      run: cp -r /home/runner/.local/share/godot/builds/0/* build
    - name: Deploy to GitHub Pages
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: build/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
